[package]
name = "common-validation"
version = "0.1.0"
edition = "2021"

[dependencies]
common-errors = { path = "../errors" }
common-models = { path = "../models" }
common-config = { path = "../config" }
common-fs = { path = "../fs" }
common-markdown = { path = "../markdown" }
regex = { workspace = true }
slug = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
common-test-utils = { path = "../test_utils" }
proptest = "1.3.1"

[[test]]
name = "slug_validation_tests"
path = "tests/slug_validation_tests.rs" 