title: The Essential Path
description: Clarity in Thought. Simplicity in Action. Engineering, Philosophy, Productivity, and the Art of Living by Evan Sims.
url: https://evansims.com
author: Evan Sims
email: hello@evansims.com
