name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: |
          for dir in tools/*/; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Testing $dir"
              cd "$dir"
              cargo test --all-features
              cd ../..
            fi
          done

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy,rustfmt

      - name: Run Clippy
        run: |
          for dir in tools/*/; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Running Clippy on $dir"
              cd "$dir"
              cargo clippy --all-features -- -D warnings
              cd ../..
            fi
          done

      - name: Check formatting
        run: |
          for dir in tools/*/; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Checking formatting in $dir"
              cd "$dir"
              cargo fmt --all -- --check
              cd ../..
            fi
          done

  security:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
