name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    uses: ./.github/workflows/rust-setup.yml
    with:
      rust-toolchain: stable
      components: clippy,rustfmt,llvm-tools-preview
      targets: x86_64-unknown-linux-gnu

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick nasm

      - name: Install Nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Run tests with Nextest
        working-directory: tools
        run: |
          cargo nextest run --workspace --all-features --profile ci
          cargo nextest run --workspace --all-features --profile ci --no-capture --run-ignored

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm

      - name: Run Clippy
        working-directory: tools
        run: cargo clippy --workspace --all-features -- -D warnings --allow clippy::to-string-in-format-args

      - name: Check formatting
        working-directory: tools
        run: cargo fmt --all -- --check

  security:
    name: Security Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        working-directory: tools
        run: cargo audit

  image-tests:
    name: Image Processing Tests
    needs: setup
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'tools/image-optimize/') || contains(github.event.head_commit.modified, 'tools/image-build/')
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick nasm

      - name: Install Nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Test image-optimize
        working-directory: tools/image-optimize
        run: |
          cargo nextest run --all-features --profile ci
          cargo clippy --all-features -- -D warnings --allow clippy::to-string-in-format-args

      - name: Test image-build
        working-directory: tools/image-build
        run: |
          cargo nextest run --all-features --profile ci
          cargo clippy --all-features -- -D warnings --allow clippy::to-string-in-format-args
