name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    uses: ./.github/workflows/rust-setup.yml
    with:
      components: clippy,rustfmt,llvm-tools-preview

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Run tests
        run: |
          for dir in tools/*/; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Testing $dir"
              cd "$dir"
              cargo test --all-features
              cd ../..
            fi
          done

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Clippy
        run: |
          for dir in tools/*/; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Running Clippy on $dir"
              cd "$dir"
              cargo clippy --all-features -- -D warnings
              cd ../..
            fi
          done

      - name: Check formatting
        run: |
          for dir in tools/*/; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Checking formatting in $dir"
              cd "$dir"
              cargo fmt --all -- --check
              cd ../..
            fi
          done

  security:
    name: Security Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  image-tests:
    name: Image Processing Tests
    needs: setup
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'tools/image-optimize/') || contains(github.event.head_commit.modified, 'tools/image-build/')
    steps:
      - uses: actions/checkout@v3

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Test image-optimize
        working-directory: tools/image-optimize
        run: |
          cargo test --all-features
          cargo clippy --all-features -- -D warnings

      - name: Test image-build
        working-directory: tools/image-build
        run: |
          cargo test --all-features
          cargo clippy --all-features -- -D warnings
