name: Dependencies

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday
  workflow_dispatch: # Allow manual trigger

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    uses: ./.github/workflows/rust-setup.yml
    with:
      rust-toolchain: stable
      components: llvm-tools-preview

  update:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Update dependencies
        working-directory: tools
        run: cargo update --workspace

      - name: Check for security vulnerabilities
        working-directory: tools
        run: cargo audit

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: |
            Automated dependency update.

            This PR updates dependencies to their latest compatible versions.

            Please review the changes before merging.
          branch: update-deps
          delete-branch: true
          labels: |
            dependencies
            automated pr
