name: Performance Monitoring

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday
  workflow_dispatch: # Allow manual trigger

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    uses: ./.github/workflows/rust-setup.yml
    with:
      components: llvm-tools-preview

  benchmark:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run benchmarks
        run: |
          cargo bench --workspace

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: target/criterion/

      - name: Check performance regressions
        run: |
          # Compare with baseline if available
          if [ -f "target/criterion/report.json" ]; then
            echo "Analyzing benchmark results..."
            # Add custom analysis logic here
          fi
