name: Rust Setup

on:
  workflow_call:
    inputs:
      rust-toolchain:
        required: true
        type: string
      components:
        required: false
        type: string
        default: ""
      targets:
        required: false
        type: string
        default: ""
    outputs:
      rust-version:
        description: "The version of Rust that was installed"
        value: ${{ jobs.setup.outputs.rust-version }}

jobs:
  setup:
    name: Setup Rust
    runs-on: ubuntu-latest
    outputs:
      rust-version: ${{ steps.rust.outputs.toolchain }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        id: rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ inputs.rust-toolchain }}
          components: ${{ inputs.components }}
          targets: ${{ inputs.targets }}
          profile: minimal
          override: true
          cache: "cargo"

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: tools -> target
