name: Test Coverage

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday
  workflow_dispatch: # Allow manual trigger

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C instrument-coverage"
  LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"

jobs:
  setup:
    uses: ./.github/workflows/rust-setup.yml
    with:
      rust-toolchain: stable
      components: llvm-tools-preview

  coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install grcov
        run: cargo install grcov

      - name: Build
        working-directory: tools
        run: cargo build --workspace

      - name: Run tests
        working-directory: tools
        run: cargo test --workspace

      - name: Generate coverage
        working-directory: tools
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: tools/lcov.info
          name: code-coverage
          fail_ci_if_error: true
          verbose: true

      - name: Check coverage threshold
        working-directory: tools
        run: |
          COVERAGE_PCT=$(lcov --summary lcov.info | grep "lines" | cut -d ":" -f 2 | cut -d "%" -f 1 | xargs)
          echo "Current coverage: $COVERAGE_PCT%"
          if (( $(echo "$COVERAGE_PCT < 60" | bc -l) )); then
            echo "Coverage below threshold of 60%"
            exit 1
          fi

      - name: Create issue if coverage below threshold
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Test Coverage Below Threshold',
              body: 'The test coverage has fallen below the required threshold of 60%. Please review and add more tests.',
              labels: ['coverage', 'needs-attention']
            });
