name: Test Coverage

on:
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday
  workflow_dispatch: # Allow manual trigger

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    uses: ./.github/workflows/rust-setup.yml
    with:
      rust-toolchain: stable
      components: llvm-tools-preview

  coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-llvm-cov and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-nextest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick nasm

      - name: Generate coverage with llvm-cov
        working-directory: tools
        run: |
          cargo llvm-cov nextest --workspace --all-features --profile coverage --lcov --output-path lcov.info
          cargo llvm-cov report --summary-only

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: tools/lcov.info
          name: code-coverage
          fail_ci_if_error: true
          verbose: true

      - name: Check coverage threshold
        working-directory: tools
        run: |
          COVERAGE_PCT=$(cargo llvm-cov report --summary-only | grep "TOTAL" | awk '{print $4}' | tr -d '%')
          echo "Current coverage: $COVERAGE_PCT%"
          if (( $(echo "$COVERAGE_PCT < 80" | bc -l) )); then
            echo "Coverage below threshold of 80%"
            exit 1
          fi

      - name: Create issue if coverage below threshold
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Test Coverage Below Threshold',
              body: 'The test coverage has fallen below the required threshold of 80%. Please review and add more tests.',
              labels: ['coverage', 'needs-attention']
            });

      - name: Generate HTML coverage report
        working-directory: tools
        run: |
          cargo llvm-cov report --html
          zip -r coverage-report.zip target/llvm-cov/html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: tools/coverage-report.zip
          retention-days: 7
